# Generated by Django 5.2.6 on 2025-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('ventas', 'Ventas'), ('cotizaciones', 'Cotizaciones'), ('produccion', 'Produccion'), ('diseño', 'Diseno')], default='admin', max_length=20),
        ),
    ]
