# Generated by Django 5.2.6 on 2025-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
