# Generated by Django 5.2.6 on 2025-09-29 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('orden', 'Vinculado a Orden'), ('libre', 'Independiente / Cliente')], default='libre', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(blank=True, help_text='Dejar vacío para diseños independientes o prediseños', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disenos', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Diseño',
                'verbose_name_plural': 'Diseños',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='disenos/archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dwg', 'jpg', 'jpeg', 'png', 'svg'])])),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='diseno.diseno')),
            ],
        ),
    ]
