# Generated by Django 5.2.6 on 2025-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_archivos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='nit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
